spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:data.sql
  config:
    import: optional:file:.env[.properties]

security:
  jwt:
    token:
      secret-key: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
      expire-length: 36000000 # 60 minutes

api:
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: ${SENDGRID_FROM_EMAIL}
    base-url: https://api.sendgrid.com/
    end-point: v3/mail/send
