spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.0.35:3306/mission?characterEncoding=UTF-8
    username: user
    password: "0000"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:data.sql
  config:
    import: optional:file:.env[.properties]

security:
  jwt:
    token:
      secret-key: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
      expire-length: 36000000 # 60 minutes

api:
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: ${SENDGRID_FROM_EMAIL}
    base-url: https://api.sendgrid.com/
    end-point: v3/mail/send
